<?php
echo '<!DOCTYPE html>';
echo '<html>';
echo '<head>';
echo '<meta name="viewport" content="width=device-width, initial-scale=1">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">';
echo '<!-- Latest compiled and minified CSS -->';
echo '<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">';
echo '';
echo '<!-- Optional theme -->';
echo '<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css" integrity="sha384-6pzBo3FDv/PJ8r2KRkGHifhEocL+1X2rVCTTkUfGk7/0pbek5mMa1upzvWbrUbOZ" crossorigin="anonymous">';
echo '';
echo '<!-- Latest compiled and minified JavaScript -->';
echo '<script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>';
echo '<style>';
echo '';
echo 'header{';
echo 'background-color: linen;';
echo 'color: green;';
echo 'text-align: center;';
echo '}';
echo 'section{';
echo 'width: 80%;';
echo 'margin-right:auto;';
echo 'margin-left:auto;';
echo '';
echo '}';
echo 'footer{';
echo '';
echo '}';
echo '</style>';
echo '';
echo '</head>';
echo '';
echo '<body class="bg-success">';
echo '<div class="container-fluid">';
echo '';
echo '<header class="bg-primary">';
echo '<h1 class="">HUG</h1>';
echo '<p>Hippe og unge grafikere AS</p>';
echo '</header>';
echo '';
echo '';
echo '<section>';
echo '<img class="img-thumbnail" width="32%" src="https://live.staticflickr.com/65535/51686507924_b0afa06569_q.jpg" width="150" height="150" alt="maths"><script async src="//embedr.flickr.com/assets/client-code.js" charset="utf-8"></script>';
echo '<img class="img-thumbnail" width="32%" src="https://live.staticflickr.com/65535/51685821156_351a90c42a_q.jpg" width="150" height="150" alt="johan"><script async src="//embedr.flickr.com/assets/client-code.js" charset="utf-8"></script>';
echo '<img class="img-thumbnail" width="32%" src="https://live.staticflickr.com/65535/51686096968_ac50c11644_q.jpg" alt="håvard"><script async src="//embedr.flickr.com/assets/client-code.js" charset="utf-8"></script>';
echo '</section>';
echo '';
echo '</div>';
echo '</body>';
echo '</html>';
?>
